package com.studentmanagement.service;

import com.studentmanagement.dao.MarkDAO;
import com.studentmanagement.model.Mark;
import com.studentmanagement.util.ValidationUtil;

import java.sql.SQLException;
import java.util.List;
import java.util.OptionalDouble;

/** Business rules for subject marks. */
public class MarkService {

    private static final int MAX_SUBJECT_LENGTH = 80;

    private final MarkDAO markDAO = new MarkDAO();

    /** @return the id generated by MySQL */
    public int addMark(int studentId, String subject, String marksText) throws ServiceException {
        if (studentId <= 0) {
            throw new ServiceException("Select a student first.");
        }
        Mark mark = buildMark(0, studentId, subject, marksText);
        try {
            ensureSubjectIsNew(mark);
            return markDAO.insert(mark);
        } catch (SQLException e) {
            throw DatabaseErrors.translate(e);
        }
    }

    public void updateMark(int markId, int studentId, String subject, String marksText) throws ServiceException {
        if (markId <= 0) {
            throw new ServiceException("Select a mark from the table to update.");
        }
        Mark mark = buildMark(markId, studentId, subject, marksText);
        try {
            ensureSubjectIsNew(mark);
            if (markDAO.update(mark) == 0) {
                throw new ServiceException("Mark not found. It may have been deleted.");
            }
        } catch (SQLException e) {
            throw DatabaseErrors.translate(e);
        }
    }

    public void deleteMark(int markId) throws ServiceException {
        if (markId <= 0) {
            throw new ServiceException("Select a mark from the table to delete.");
        }
        try {
            if (markDAO.delete(markId) == 0) {
                throw new ServiceException("Mark not found. It may have already been deleted.");
            }
        } catch (SQLException e) {
            throw DatabaseErrors.translate(e);
        }
    }

    public List<Mark> getMarks(int studentId) throws ServiceException {
        try {
            return markDAO.findByStudent(studentId);
        } catch (SQLException e) {
            throw DatabaseErrors.translate(e);
        }
    }

    private void ensureSubjectIsNew(Mark mark) throws SQLException, ServiceException {
        if (markDAO.subjectExists(mark.getStudentId(), mark.getSubject(), mark.getMarkId())) {
            throw new ServiceException("This student already has marks for '" + mark.getSubject()
                    + "'. Select that row and use Update instead.");
        }
    }

    private Mark buildMark(int markId, int studentId, String subject, String marksText) throws ServiceException {
        if (ValidationUtil.isBlank(subject)) {
            throw new ServiceException("Subject is required.");
        }
        if (!ValidationUtil.isWithinLength(subject.trim(), MAX_SUBJECT_LENGTH)) {
            throw new ServiceException("Subject must be at most " + MAX_SUBJECT_LENGTH + " characters.");
        }
        if (ValidationUtil.isBlank(marksText)) {
            throw new ServiceException("Marks are required.");
        }
        OptionalDouble parsed = ValidationUtil.parseNumber(marksText);
        if (parsed.isEmpty()) {
            throw new ServiceException("Marks must be a number, for example 78 or 78.5.");
        }
        if (!ValidationUtil.isValidMarks(parsed.getAsDouble())) {
            throw new ServiceException("Marks must be between " + (int) ValidationUtil.MIN_MARKS
                    + " and " + (int) ValidationUtil.MAX_MARKS + ".");
        }
        Mark mark = new Mark();
        mark.setMarkId(markId);
        mark.setStudentId(studentId);
        mark.setSubject(subject.trim());
        mark.setMarks(parsed.getAsDouble());
        return mark;
    }
}
