package com.studentmanagement.service;

import com.studentmanagement.dao.StudentDAO;
import com.studentmanagement.model.DashboardStats;
import com.studentmanagement.model.SearchField;
import com.studentmanagement.model.Student;
import com.studentmanagement.util.ValidationUtil;

import java.sql.SQLException;
import java.util.List;

/** Business rules for student records: validation, duplicate checks, and CRUD. */
public class StudentService {

    private static final int MAX_NAME_LENGTH = 100;
    private static final int MAX_TEXT_LENGTH = 80;

    private final StudentDAO studentDAO = new StudentDAO();

    /** @return the id generated by MySQL */
    public int addStudent(Student student) throws ServiceException {
        normalize(student);
        validate(student);
        try {
            if (studentDAO.emailExists(student.getEmail(), 0)) {
                throw new ServiceException("Another student already uses this email address.");
            }
            return studentDAO.insert(student);
        } catch (SQLException e) {
            throw DatabaseErrors.translate(e);
        }
    }

    public void updateStudent(Student student) throws ServiceException {
        if (student.getStudentId() <= 0) {
            throw new ServiceException("Select a student to update.");
        }
        normalize(student);
        validate(student);
        try {
            if (studentDAO.emailExists(student.getEmail(), student.getStudentId())) {
                throw new ServiceException("Another student already uses this email address.");
            }
            if (studentDAO.update(student) == 0) {
                throw new ServiceException("Student not found. It may have been deleted.");
            }
        } catch (SQLException e) {
            throw DatabaseErrors.translate(e);
        }
    }

    public void deleteStudent(int studentId) throws ServiceException {
        if (studentId <= 0) {
            throw new ServiceException("Select a student to delete.");
        }
        try {
            if (studentDAO.delete(studentId) == 0) {
                throw new ServiceException("Student not found. It may have already been deleted.");
            }
        } catch (SQLException e) {
            throw DatabaseErrors.translate(e);
        }
    }

    public List<Student> getAllStudents() throws ServiceException {
        try {
            return studentDAO.findAll();
        } catch (SQLException e) {
            throw DatabaseErrors.translate(e);
        }
    }

    public List<Student> search(SearchField field, String keyword) throws ServiceException {
        if (ValidationUtil.isBlank(keyword)) {
            throw new ServiceException("Enter something to search for.");
        }
        String trimmed = keyword.trim();
        if (field == SearchField.STUDENT_ID && ValidationUtil.parsePositiveInt(trimmed).isEmpty()) {
            throw new ServiceException("Student ID must be a positive whole number.");
        }
        try {
            return studentDAO.search(field, trimmed);
        } catch (SQLException e) {
            throw DatabaseErrors.translate(e);
        }
    }

    public DashboardStats getDashboardStats() throws ServiceException {
        try {
            return studentDAO.getStats();
        } catch (SQLException e) {
            throw DatabaseErrors.translate(e);
        }
    }

    private void normalize(Student student) {
        student.setName(trim(student.getName()));
        student.setEmail(trim(student.getEmail()).toLowerCase());
        student.setPhone(trim(student.getPhone()));
        student.setDepartment(trim(student.getDepartment()));
        student.setCourse(trim(student.getCourse()));
    }

    private String trim(String value) {
        return value == null ? "" : value.trim();
    }

    private void validate(Student student) throws ServiceException {
        if (ValidationUtil.isBlank(student.getName())) {
            throw new ServiceException("Full name is required.");
        }
        if (!ValidationUtil.isValidName(student.getName())
                || !ValidationUtil.isWithinLength(student.getName(), MAX_NAME_LENGTH)) {
            throw new ServiceException("Name may contain only letters, spaces, dots, hyphens and apostrophes.");
        }
        if (ValidationUtil.isBlank(student.getEmail())) {
            throw new ServiceException("Email is required.");
        }
        if (!ValidationUtil.isValidEmail(student.getEmail())) {
            throw new ServiceException("Enter a valid email address, for example name@example.com.");
        }
        if (ValidationUtil.isBlank(student.getPhone())) {
            throw new ServiceException("Phone number is required.");
        }
        if (!ValidationUtil.isValidPhone(student.getPhone())) {
            throw new ServiceException("Phone number must be 10 digits and start with 6, 7, 8 or 9.");
        }
        if (!ValidationUtil.isValidGender(student.getGender())) {
            throw new ServiceException("Select a gender.");
        }
        if (student.getDateOfBirth() == null) {
            throw new ServiceException("Date of birth is required (format YYYY-MM-DD).");
        }
        if (!ValidationUtil.isValidDateOfBirth(student.getDateOfBirth())) {
            throw new ServiceException("Date of birth must be between 1900-01-01 and today.");
        }
        requireText(student.getDepartment(), "Department");
        requireText(student.getCourse(), "Course");
        if (!ValidationUtil.isValidYear(student.getYear())) {
            throw new ServiceException("Year must be between " + ValidationUtil.MIN_YEAR
                    + " and " + ValidationUtil.MAX_YEAR + ".");
        }
    }

    private void requireText(String value, String fieldName) throws ServiceException {
        if (ValidationUtil.isBlank(value)) {
            throw new ServiceException(fieldName + " is required.");
        }
        if (!ValidationUtil.isWithinLength(value, MAX_TEXT_LENGTH)) {
            throw new ServiceException(fieldName + " must be at most " + MAX_TEXT_LENGTH + " characters.");
        }
    }
}
